### ISSUE TITLE
Create App Opener animation

### ISSUE THREAD

**Issue by ranjitodedra** [ranjitodedra/Trendit#7]
# Add Opener

- Add animation --> Increasing the size of the logo for a certain level

- then redirect to the home page of the app

**Comment by YajanaRao** [comment]
Are you refering to expo splash screen ?
https://docs.expo.dev/guides/splash-screens/

**Comment by ranjitodedra** [comment]
> Are you refering to expo splash screen ? https://docs.expo.dev/guides/splash-screens/

Yes

**Comment by YajanaRao** [comment]
I can work on it.

**Comment by YajanaRao** [comment]
@ranjitodedra What would be the logo for splash screen ?

**Comment by ranjitodedra** [comment]
> @ranjitodedra What would be the logo for splash screen ?

Logo is available in asset folder 📂
Choose any one of them

**Comment by YajanaRao** [comment]
@ranjitodedra how does this look ?
![expo-splash-screen-animation](https://user-images.githubusercontent.com/38914337/196450036-27139353-2490-4df0-a33c-a44d625206c8.gif)

**Comment by YajanaRao** [comment]
Here is my PR with these changes: #9
